# Generated by Django 4.2.2 on 2023-07-02 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0002_product_remove_profile_date_modified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_description',
            field=models.CharField(default='', max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_link',
            field=models.CharField(default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_price',
            field=models.CharField(default='', max_length=500, null=True),
        ),
    ]
