# Generated by Django 4.2.7 on 2024-05-12 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0018_alter_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
    ]
